name: pr1nter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2

  # others
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  smooth_page_indicator: ^2.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5

  pdf: ^3.11.3
  photo_manager: ^3.8.3
  printing: ^5.14.2
  screenshot: ^3.0.0
  permission_handler: ^12.0.1
  in_app_review: ^2.0.11
  flutter_inappwebview: ^6.1.5
  # receive_sharing_intent: ^1.8.1

  # picker
  image_picker: ^1.2.1
  file_picker: ^10.3.7

  # scanner
  cunning_document_scanner: ^1.4.0
  google_mlkit_text_recognition: ^0.15.0

  # vip
  purchases_flutter: ^9.10.0
  purchases_ui_flutter: ^9.10.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # change_app_package_name: ^1.5.0 
  # dart run change_app_package_name:main com.example.test1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/home/
    - assets/icons/
    - assets/onboard/
    - assets/printables/
  fonts:
    - family: w500
      fonts:
        - asset: assets/fonts/WixMadeforText-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/WixMadeforText-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/WixMadeforText-Bold.ttf
