name: pr1nter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

  # others
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  smooth_page_indicator: ^1.2.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

  # network
  dio: ^5.9.0

  # db
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # vip
  purchases_flutter: ^9.9.5
  purchases_ui_flutter: ^9.9.5
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # change_app_package_name: ^1.5.0 
  # dart run change_app_package_name:main com.example.test1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/home/
    - assets/icons/
  fonts:
    - family: w500
      fonts:
        - asset: assets/fonts/WixMadeforText-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/WixMadeforText-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/WixMadeforText-Bold.ttf
